### ISSUE TITLE
is this project still active?

### ISSUE THREAD

**Issue by erichaus** [ember-data/ember-data-filter#10]
Is it sill active or is there a different path that was taken?

**Comment by erichaus** [comment]
??? how should I be filtering an array full of ember-data records?

**Comment by CodeDeFury** [comment]
With `store.filter`, 
```
store.filter('post', function (post) {
  return post.get('type') === 1;
})

// post with type 1 added, will trigger update
// post with type 2 added, will not trigger update
```

With the propose `peekAll` + computed property approach,
```
posts: Ember.computed(function() {
  return this.store.peekAll('post');
}),

filteredPosts: Ember.computed('posts.@each.type', function() {
  return this.get('posts').filterBy('type', 1);
})

// post with type 1 added, will trigger update
// post with type 2 added, will trigger update
```
Would like to avoid triggering the extra update.

Sorry for commenting on a closed issue. Need some advice here. I'm just thinking the same thing as @erichonkanen 

> ??? how should I be filtering an array full of ember-data records?
