### ISSUE TITLE
Ember App Kit

### ISSUE THREAD

**Issue by sergiferran** [ember-data/ember-data-filter#3]
Hi!

We are still using Ember App Kit and we are getting the deprecation, but as far as i know this add on is only for ember CLI, any solution?

Thank you so much

**Comment by pangratz** [comment]
I think [ember-giftwrap](https://github.com/ef4/ember-giftwrap) might help you here...

**Comment by bmac** [comment]
Hi @sergiferran, peeling back the curtains a bit currently all this addon does is set  `EmberENV.ENABLE_DS_FILTER` to true. For now you can do that manually. However, in the future we may end up moving more code supporting filtering out of Ember Data and into this repo.

**Comment by sergiferran** [comment]
@bmac Thank you, it works.
BTW, we are planning to migrate it to ember-cli in a future, so everything will fit then.
